services:
  - type: web
    name: vChat
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "daphne -b 0.0.0.0 -p 10000 config.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"